import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/navbar/MainNav";
import { Footer } from "@/components/footer/Footer";
import RequestDemo from "@/components/_pages/homepage/RequestDemo";
import { Suspense } from "react";
import Loading from "./loading";
import MobileNavbar from "@/components/navbar/MobileNavbar";
import MobileNavbarNew from "@/components/navbar/MobileNavbarNew";
const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "1ClickDesign | THE FUTURE OF SALES AND MARKETING IS HERE TODAY",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <head>
    <link
     rel="icon"
     href="/1clickdesign-logo-black.svg"
    />
   </head>
   <body className={`${raleway.className} overflow-x-hidden`}>
    <Suspense fallback={<Loading />}>
     <MainNav />
     {/* <MobileNavbar></MobileNavbar> */}
     <MobileNavbarNew></MobileNavbarNew>
     {children}
     <RequestDemo></RequestDemo>
     <Footer />
    </Suspense>
   </body>
  </html>
 );
}
